name: Auto Convert and Version Update

on:
  push:
    branches:
      - main

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: do something
        run: |
          echo "do something"
