name: Create Figma Tokens Pull Request (automatic create pull request)

# match the branch you put in your Figma Tokens Sync Credentials in the next step
on:
  push:
    branches:
      - figma-tokens

jobs:
  # convert-sd:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         repository: ${{ github.event.pull_request.head.repo.full_name }}
  #         ref: ${{ github.event.pull_request.head.ref }}
  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Run token-transformer
  #       run: npx token-transformer sd-input/src/figma-tokens-output.json sd-input/src/sd-input.json global,colors,size,font global --resolveReferences true --expandTypography=true

  #     - name: Run style-dictionary
  #       run: npx style-dictionary build --config sd.config.cjs

  #     - name: Commit changes
  #       uses: EndBug/add-and-commit@v9
  #       with:
  #         author_name: senno adi
  #         author_email: senno.adi2509@@gmail.com
  #         message: 'chore: style-dictionary output'
  #         add: '.'

  pull-request:
    runs-on: ubuntu-latest
    # needs: convert-sd
    steps:
      # - name: skip process
      #   run: |
      #     echo "skipped"

      #     - name: Check Branch Name
      #       run: |
      #         if [[ $GITHUB_REF != "refs/heads/figma-tokens" ]]; then
      #           echo "Not pushing to figma-tokens branch, skipping the workflow."
      #           exit 0
      #         fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Branch tujuan pull request
          title: 'Figma Tokens Update'
          body: '🍥 Design Tokens were updated in Figma! This PR was created to update the code.'

  # uses: repo-sync/pull-request@v2
  # with:
  #   destination_branch: 'main' # match your default branch
  #   pr_title: 'Figma Tokens Update'
  #   pr_body: '🍥 Design Tokens were updated in Figma! This PR was created to update the code.'
  #   github_token: ${{ secrets.GITHUB_TOKEN }}

  # - uses: actions/checkout@v2

  # - name: Create Pull Request
  #   uses: repo-sync/pull-request@v2
  #   with:
  #     destination_branch: 'main' # match your default branch
  #     pr_title: 'Figma Tokens Update'
  #     pr_body: '🍥 Design Tokens were updated in Figma! This PR was created to update the code.'
  #     github_token: ${{ secrets.GITHUB_TOKEN }}
