name: Create Figma Tokens Pull Request (automatic create pull request)

# match the branch you put in your Figma Tokens Sync Credentials in the next step
on:
  push:
    branches:
      - figma-tokens

jobs:
  convert-sd:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run token-transformer
        run: npx token-transformer sd-input/src/figma-tokens-output.json sd-input/src/sd-input.json global,colors,size,font global --resolveReferences true --expandTypography=true

      - name: Run style-dictionary
        run: npx style-dictionary build --config sd.config.cjs

      - name: Commit changes
        run: |
          git config --local user.email "senno.adi2509@gmail.com"
          git config --local user.name "senno adi"
          git add .
          git commit -m "chore: style-dictionary output"
          git push origin main

  pull-request:
    needs: convert-sd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Branch tujuan pull request
          title: 'Figma Tokens Update'
          body: '🍥 Design Tokens were updated in Figma! This PR was created to update the code.'
