name: Create Figma Tokens Pull Request (automatic create pull request)

# match the branch you put in your Figma Tokens Sync Credentials in the next step
on:
  push:
    branches:
      - figma-tokens

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Branch tujuan pull request
          title: 'Figma Tokens Update'
          body: '🍥 Design Tokens were updated in Figma! This PR was created to update the code.'
